### ISSUE TITLE
Automatically Select the Tags on Pressing Tab

### ISSUE THREAD

**Issue by zeshanshani** [Box-Of-Hats/Bem-VSCode-Extension#11]
When you insert the element and press tab, it takes you to the tags placeholder (see: https://s.zeshanahmed.com/a_234B8430.png), then you manually have to select both `div` tags to overwrite them. 

I think it's much better UX if it by defaults select both `div` tags which you can directly overwrite without having to select them first. 

Hope I explained it fine. 

Thanks!

**Comment by Box-Of-Hats** [comment]
As a potential fix for this, I could remove the suggestion list of elements and instead allow the user to type any element they like in that place.

I'll have a play around with this idea later and see how it feels to use

**Comment by Box-Of-Hats** [comment]
I've removed the tag list functionality from inserted snippets as they seemed to be causing more trouble than help.

Now when inserting new elements, you'll be able to type any element you like and you should no longer need to press TAB twice.

I've just released this as part of the 0.8.0 release

**Comment by zeshanshani** [comment]
This is perfect Jake. Works exactly how I was expecting it! :)
