### ISSUE TITLE
Insert Element - Attribute Insert misbehaviour

### ISSUE THREAD

**Issue by zeshanshani** [Box-Of-Hats/Bem-VSCode-Extension#12]
Possibly misbehavior. When you Insert Element and then press `TAB` the 2nd time, it takes you to the attribute place, however, it takes it to both opening and closing tags (see: https://s.zeshanahmed.com/a_234B8580.png). I think it was meant to take only to the opening tag?

**Comment by Box-Of-Hats** [comment]
This is intended. For the reason that the closing tag needs to match the opening tag.
If only the opening tag was selected then it would be possible to open a `<H1>` tag with a `</div>` closing

**Comment by zeshanshani** [comment]
@Box-Of-Hats I explained that one as well in separate issue: #11

**Comment by Box-Of-Hats** [comment]
I've just released version 0.8.0 of the extension which includes a slight change in the insert element snippets.

Has this fixed this issue for you?

**Comment by zeshanshani** [comment]
@Box-Of-Hats yes, it works perfectly. Thanks a lot! 👍
