### ISSUE TITLE
allow _modifier-name

### ISSUE THREAD

**Issue by furtivite** [Box-Of-Hats/Bem-VSCode-Extension#13]
Thanks for plugin.
Version: 0.7.5

My settings of plugin looks like

`{
    "editor.largeFileOptimizations": false,
    "explorer.confirmDragAndDrop": false,
    "editor.minimap.enabled": true,
    "window.zoomLevel": 0,
    "explorer.confirmDelete": false,
    "terminal.integrated.shell.windows": "D:\\Program Files\\Git\\git-bash.exe",
    "terminal.external.windowsExec": "D:\\Program Files\\Git\\git-bash.exe",
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    **"bemHelper.modifierSeparator": "_"**
}`

and extansion setting looks like
![2019-10-08_09-35-02](https://user-images.githubusercontent.com/50330458/66372917-f32ef400-e9af-11e9-9dbc-c69349b62388.png).

By default BEM metodology uses `_` as `.modifierSepararor` [link](https://en.bem.info/methodology/quick-start/#modifier). But if I configure the plugin as above, it does not work correctly, and emphasizes classes with modifier because it considers ` _ ' as part of the class name. 
![2019-10-08_09-39-44](https://user-images.githubusercontent.com/50330458/66372944-03df6a00-e9b0-11e9-8691-3a283c9f06e1.png)

**Comment by Box-Of-Hats** [comment]
Thanks for the detailed bug report. I'll look into this issue later today

**Comment by Box-Of-Hats** [comment]
Thanks for bringing this up. I've now fixed this bug and it is available in the 0.8.0 release of BEM Helper.

Let me know if you find any more bugs

**Comment by mr9d** [comment]
Thank you for the quick fix, sir!

**Comment by furtivite** [comment]
Thanks, it's fixed.
