### ISSUE TITLE
Non Alphabetic Style Sheet Generate

### ISSUE THREAD

**Issue by gkelley** [Box-Of-Hats/Bem-VSCode-Extension#14]
Any chance you could add a setting that would allow for generating a style sheet in Top to Bottom order instead of alphabetical?

**Comment by Box-Of-Hats** [comment]
Thanks for your suggestion :)

This has been added and is now included in the 0.8.0 release of the extension.

Use the new setting `bemHelper.sortGeneratedStylesheets` to enable and disable alphabetic sorting of generated stylesheet classes
