### ISSUE TITLE
_key-value separator in _modifiers

### ISSUE THREAD

**Issue by furtivite** [Box-Of-Hats/Bem-VSCode-Extension#16]
Hi, in BEM methodology, it is permissible to set _modifiers with an additional _key-value. For example: 

`block-name__element-name_modifier-name_modifier-value`

[Read more](https://en.bem.info/methodology/quick-start/#modifier)

Unfortunately, now the extantion handles such classes as an error. Although _ is set as the modifier separator, it is suggested to use kebab case instead of _ when using _key-value.

![2019-10-12_14-18-16](https://user-images.githubusercontent.com/50330458/66700619-34e6d400-ecfb-11e9-8923-73901a1e6c1a.png)

It would be super cool if you added a rule to the plugin settings to separate modifiers and modifier values, according to the [BEM naming convention](https://en.bem.info/methodology/naming-convention/). And also improved handling of key-value modifiers.

Thanks a lot.

**Comment by AradAral** [comment]
I was quite shocked to see this.
Isn't this extension supposed to conform to BEM standards?! If yes, then key-value modifiers are a thing in BEM. It shouldn't give you a warning when you have such class names.

**Comment by Box-Of-Hats** [comment]
Hi both, thanks for the feedback.

BEM Helper is based on the docs at [getbem](http://getbem.com/) which doesn't feature the key-value modifiers (as far as I can tell). I don't use key-value modifiers personally but I am interested in supporting them so that other people can make use of them.

I will be looking into this feature shortly so if there's any more examples and/or test cases you can provide, they would be greatly appreciated so that I can get this right 😊

**Comment by AradAral** [comment]
@Box-Of-Hats Hi!
Thanks!
I think the only thing to take into account is that the separator of block or element name and the modifier name, is the separator between the modifier name and modifier value. For instance:
If you use underscore (_) as the separator of block/element name and the modifier name, it would be like this:
```
block__element_modifier-name_modifier-value
```
And if you use a double-dash (--) as the separator between block/element name and modifier, then it would like this:
```
block__element--modifier-name--modifier-value
```

As far as I know, there is nothing beyond this. That's all.

**Comment by Box-Of-Hats** [comment]
I've added now support for this in version `1.4.0`. Let me know if that's now working as expected for you 😊
