### ISSUE TITLE
How can I disable a warning?

### ISSUE THREAD

**Issue by haoxf** [Box-Of-Hats/Bem-VSCode-Extension#17]

**Comment by Box-Of-Hats** [comment]
To turn off class name casing warnings, use the setting `bemHelper.classNameCase: "any",`

To turn off depth warnings, use the setting: `bemHelper.showDepthWarnings: false,`

To turn off all warnings, use `bemHelper.maxWarningsCount: 0,`

The full list of settings are available in the [repo readme.](https://github.com/Box-Of-Hats/Bem-VSCode-Extension#settings)
