### ISSUE TITLE
Templating support

### ISSUE THREAD

**Issue by bm-stschneider** [Box-Of-Hats/Bem-VSCode-Extension#2]
Is there support for html like templating like twig, smarty, handlebars ...

**Comment by Box-Of-Hats** [comment]
I don't know enough about those template frameworks to say for certain but at a glance, they look like they should be supported

**Comment by Box-Of-Hats** [comment]
You'll be pleased to know that Twig is now officially supported

**Comment by hinogi** [comment]
Yay
