### ISSUE TITLE
Mac hot-keys

### ISSUE THREAD

**Issue by Fainorthegreat** [Box-Of-Hats/Bem-VSCode-Extension#20]
Hello!

Thank you for application.

I have a question.
How can i use hot-keys on mac?

When i push option+b e -  vscode say me its not correct.

**Comment by Box-Of-Hats** [comment]
If you open the shortcuts menu in VSCode, you should be able to see (and set your own) shortcuts.

Alternatively, you can only the command palette and type `BEM Helper: Insert Element` which will display the shortcut next to the command
