### ISSUE TITLE
Generated stylesheets come in only one line.

### ISSUE THREAD

**Issue by akumanara** [Box-Of-Hats/Bem-VSCode-Extension#22]
I have disabled everything and returned to factory settings but this extension still generated the stylesheet in one line.

**Comment by akumanara** [comment]
You need to have a formatter for your generated language installed.

**Comment by Box-Of-Hats** [comment]
You're right that the extension requires a formatter to be installed for the output not to be on one line. This shouldn't be too much of an issue but I may add some basic formatting to the extension just to stop this from happening.

Thanks for your input :)
