### ISSUE TITLE
Insert newline after any inserted elements

### ISSUE THREAD

**Issue by heskitt** [Box-Of-Hats/Bem-VSCode-Extension#25]
Hey. Version 0.8.0 brought with it the insertion of a new line after the element.
Can I disable this feature?

**Comment by heskitt** [comment]
Wow! It was very fast! Thank!

**Comment by Box-Of-Hats** [comment]
I've not released the change just yet but I'll have it published on the extension store by the end of the day. Keep an  eye out for BemHelper v1.1.2 :)
