### ISSUE TITLE
Twig if statement inside classname in Camelcase detect error

### ISSUE THREAD

**Issue by rbouza23** [Box-Of-Hats/Bem-VSCode-Extension#35]
If i have something like this:
<li class="navigation__item {% if sectionKey == 'home' %}navigation__item--active{% endif %}">
  <a class="navigation__link" href="{{baseUrl}}">Home</a>
</li>

The plugin detect "sectionKey" not correct. But that is not the classname itself. Is a twig variable..

Is there a way to fix the issue?

**Comment by Box-Of-Hats** [comment]
Hi, thanks for opening an issue. Can you show some code that is having the issue?

I can try to add support for the twig language if I have some examples

**Comment by rbouza23** [comment]
`<header class="header py-4">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 col-lg-auto">
        <a href="#"><img src="{{imgPath}}logo.svg" alt="Logo"></a>
      </div>
      <div class="col mt-4 mt-lg-0">
        
        <nav class="navigation ml-lg-5">
          <ul class="navigation__list">
            <li class="navigation__item {% if sectionKey == 'home' %}navigation__item--active{% endif %}">
              <a class="navigation__link" href="{{baseUrl}}">Home</a>
            </li>
            <li class="navigation__item {% if sectionKey == 'contact' %}navigation__item--active{% endif %}">
              <a class="navigation__link" href="{{baseUrl}}contact">Contact</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>`

![Captura](https://user-images.githubusercontent.com/54042330/115621655-33717100-a2cd-11eb-8bda-4d4df1150ac2.JPG)

**Comment by Box-Of-Hats** [comment]
@rbouza23 I've added support for the twig language in version 1.4.1 of the extension. 
Please update and let me know if that's solved your issue

**Comment by rbouza23** [comment]
Thanks Jake! Its resolved!

**Comment by Box-Of-Hats** [comment]
Great to hear it 😊
