### ISSUE TITLE
svelte language support

### ISSUE THREAD

**Issue by kr40** [Box-Of-Hats/Bem-VSCode-Extension#38]
Please add Svelte language support.

[Svelte Homepage](https://svelte.dev/)

**Comment by Box-Of-Hats** [comment]
Thanks for the suggestion. Support for svelte has now been added in version [1.4.2](https://github.com/Box-Of-Hats/Bem-VSCode-Extension/releases/tag/v1.4.2).

Let me know if you find any issues 🚀
