### ISSUE TITLE
It is possible to generate the code directly to the clipboard?

### ISSUE THREAD

**Issue by macakronos** [Box-Of-Hats/Bem-VSCode-Extension#39]
Sorry if you thought it was a problem, but didn't know where to put this question. Its complement is very good, but there are times when I want to generate my code in parts and generating a new file at all times becomes tiring. Thank you so much for everything.

**Comment by Box-Of-Hats** [comment]
Hi, thanks for your suggestion! 

This is definitely something that I can add in. Is it the CSS/LESS/SCSS that you'd want copied to your clipboard?

**Comment by macakronos** [comment]
Exactly.

**Comment by Box-Of-Hats** [comment]
Thanks for the suggestion. I've added this in version [1.4.2](https://github.com/Box-Of-Hats/Bem-VSCode-Extension/releases/tag/v1.4.2). 

You'll get a prompted when generating a new stylesheet

![image](https://user-images.githubusercontent.com/9083502/116763975-527fa980-aa17-11eb-845d-94cfe73cb00a.png)
