### ISSUE TITLE
Possible improvement: Generate the classes in order of appearance in the HTML.

### ISSUE THREAD

**Issue by macakronos** [Box-Of-Hats/Bem-VSCode-Extension#44]
Hello, thank you for your excellent contribution.

I have a possible improvement proposal: Generate the classes in order of appearance in the HTML.

Currently it generates the classes but out of order, which in my opinion is better to read them in the order of appearance in the HTML, since it helps to have the file better organized. Currently what I do is order them manually. I attach a small example of what I am talking about.

Thanks for everything.

![HTML](https://user-images.githubusercontent.com/55098957/134545912-ad4bcec5-9a72-4dcd-aca1-7b0ee422f95b.png)
![CSS](https://user-images.githubusercontent.com/55098957/134546035-2ec6694a-0ef5-4974-9200-a2db8cbd3371.jpg)

**Comment by Box-Of-Hats** [comment]
Thanks again for the detailed suggestion :)

This should also already be available if you adjust the setting `bemHelper.sortGeneratedStylesheets` to `false`.

Give that a try and let me know if you're still having issues

**Comment by macakronos** [comment]
Thank you very much, there it was... hahaha
