### ISSUE TITLE
Possible new option: Skip some classes entirely.

### ISSUE THREAD

**Issue by macakronos** [Box-Of-Hats/Bem-VSCode-Extension#45]
Hello, thank you for your contribution to the community.

I want to propose the addition of a characteristic: allow to specify in the configuration which classes should be completely omitted.

For example, sometimes some css classes are used from frameworks like Bootstrap that you want to skip completely, in any case it can be removed manually, but it can take your time in a large project, with many components.

Thanks for everything.
![Config BEM](https://user-images.githubusercontent.com/55098957/134549027-6c0124e7-c7d8-4173-9666-702ef814c270.jpg)

**Comment by Box-Of-Hats** [comment]
Hi, thanks  for the recommendation :) The good news is that it's already a feature under the setting `bemHelper.ignoreClassNames`.

For example:

```json

  "bemHelper.ignoreClassNames": ["col-12", "aside"],

```

**Comment by macakronos** [comment]
I have already tried that option but I still get these classes in the generated code. Besides that in the description it says that it has another utility.

`A list of class names that should be ignored as parents (blocks) when inserting new elements`

**Comment by Box-Of-Hats** [comment]
I see now, thanks for clarifying. That will be a new feature but it sounds straightforward enough to add. I'll look at this soon! :)

**Comment by macakronos** [comment]
Thanks for your time.

**Comment by Box-Of-Hats** [comment]
[Version 1.4.3](https://github.com/Box-Of-Hats/Bem-VSCode-Extension/releases/tag/v1.4.3) has just been released which includes that fix.
The stylesheet generation will now respect your ignored classes list. 

Thanks again for your suggestion 🚀

**Comment by macakronos** [comment]
For some reason it doesn't work for me. I put "col-12" to ignore me, but it keeps generating it. I have verified that I have the latest version of the extension.

**Comment by Box-Of-Hats** [comment]
Can you paste in some example HTML where you're having the issue so I can also try with it?

**Comment by macakronos** [comment]
This is
`		<div class="inner-wrapper video-w-image">
			<div class="medium-width-wrapper">
				<div class="topper-bg--image-wrapper">
					<img class="topper-bg--image" src="">
				</div>
				<div class="row">
					<div class="col-12">
						<div class="topper-bg">
							<p class="topper-bg--sub-headline"></p>
							<h2 class="topper-bg--headline"></h2>
						</div>
					</div>
				</div>
			</div>
		</div>`

**Comment by macakronos** [comment]
My settings
`	"bemHelper.sortGeneratedStylesheets": false,
	"bemHelper.ignoreClassNames": [
	
		"video-w-image",
		"col-12", "aside",
		"material-icons"
	]`

**Comment by Box-Of-Hats** [comment]
Thanks for sending that over, it really helped with debugging this one :) 

I've released a fix in version [1.4.4](https://github.com/Box-Of-Hats/Bem-VSCode-Extension/releases/tag/v1.4.4) which  should sort this out.

**Comment by macakronos** [comment]
Thank you. It works excellent.
