### ISSUE TITLE
Support for custom element and modifier separators

### ISSUE THREAD

**Issue by UndeadRedPanda** [Box-Of-Hats/Bem-VSCode-Extension#5]
I was wondering if it would be possible to add a setting to have custom element and modifier separators. Our templating engine doesn't respond well to having `--` inside an HTML comment. When we go about commenting entire blocks of code with the normal BEM separators, we end up with errors. To make life easier for ourselves, we separate modifiers with a different separator. I wouldn't mind making my own PR if you don't have the time.

**Comment by Box-Of-Hats** [comment]
I've just added support for this so you'll be able to set your separators using the settings `bemHelper.modifierSeparator` and `bemHelper.elementSeparator`.

Thanks for your suggestion and for helping to make bemHelper better :)
