### ISSUE TITLE
Generate CSS selectors from current selection in HTML files

### ISSUE THREAD

**Issue by AloisJanicek** [Box-Of-Hats/Bem-VSCode-Extension#8]
I would really appreciate if I could generate CSS selectors from just current selection in HTML file as in opposite to generating CSS selectors for whole HTML file.
I find myself building stuff gradually and I often add new BEM components to existing HTML files. Extracting only newly added selectors / components from generated stylesheet is little inconvenient. But still 100x more convenient then writing them "manually" like I did before 👍

**Comment by Box-Of-Hats** [comment]
I can see how this would be a big help. I'll get right on it!

**Comment by Box-Of-Hats** [comment]
That's now added in version 0.7.2.

The new command `Bem Helper: Generate Stylesheet From Selection` should do exactly what you're after :)

[Commit details](https://github.com/Box-Of-Hats/Bem-VSCode-Extension/commit/e60458f1a76b63a3ff991727f87ff42b1709ccaf)

**Comment by AloisJanicek** [comment]
Thank your very much, you are awesome. Works flawlessly 👍

**Comment by Box-Of-Hats** [comment]
Thanks for the suggestion. I'm glad I could be of help
